/* ============================================================
   CRAB Design Studio — Journal (grid)
   Loads post cards from blog-posts.json and links each one to
   its own real page at blog/<slug>/ (generated by build-blog.mjs).
   ============================================================ */
(function () {
  'use strict';

  var grid    = document.getElementById('post-grid');
  var elLoad  = document.getElementById('blog-loading');
  var elEmpty = document.getElementById('blog-empty');
  var elError = document.getElementById('blog-error');

  function show(el) { if (el) el.hidden = false; }
  function hide(el) { if (el) el.hidden = true; }

  function load() {
    return fetch('blog-posts.json', { cache: 'no-store' })
      .then(function (r) { if (!r.ok) throw new Error(r.status); return r.json(); })
      .then(function (data) { return (data && data.posts) || []; });
  }

  function fmtDate(iso) {
    if (!iso) return '';
    var d = new Date(iso);
    if (isNaN(d)) return iso;
    return d.toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });
  }

  function esc(s) {
    return String(s == null ? '' : s)
      .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;');
  }

  // The CMS may write image paths with a leading slash (/assets/blog/x.jpg),
  // which is absolute from the domain root and breaks on a project site served
  // under /crab/. Strip it so paths stay relative to the page.
  function assetUrl(p) {
    if (!p) return '';
    if (/^https?:\/\//i.test(p)) return p;
    return p.replace(/^\/+/, '');
  }

  function render(posts) {
    hide(elLoad);

    if (!posts.length) { show(elEmpty); return; }

    posts.forEach(function (post, i) {
      var card = document.createElement('a');
      card.className = 'post';
      card.href = 'blog/' + post.slug + '/';
      card.style.setProperty('--i', i);

      var meta = [post.category, fmtDate(post.date)].filter(Boolean).join('  ·  ');

      card.innerHTML =
        '<span class="post__media">' +
          (post.image ? '<img src="' + esc(assetUrl(post.image)) + '" alt="" loading="lazy">' : '') +
        '</span>' +
        '<span class="post__meta">' + esc(meta) + '</span>' +
        '<span class="post__title">' + esc(post.title || 'Untitled') + '</span>' +
        '<span class="post__excerpt">' + esc(post.excerpt || '') + '</span>' +
        '<span class="post__more">Read <span aria-hidden="true">&rarr;</span></span>';

      grid.appendChild(card);
    });
  }

  load()
    .then(render)
    .catch(function () { hide(elLoad); show(elError); });
})();
